/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DoorPanel.java
 *
 * Created on 30.03.2011, 13:24:57
 */

package de.htwhome.gui.panel;

import de.htwhome.devices.Panel;

/**
 *
 * @author tim
 */
public class DoorPanel extends javax.swing.JPanel {
    Panel panel;

    /** Creates new form DoorPanel */
    public DoorPanel(Panel panel) {
	this.panel = panel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webcamIconLabel = new javax.swing.JLabel();
        openDoorButton = new javax.swing.JButton();

        webcamIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/htwhome/gui/panel/webcam.jpg"))); // NOI18N

        openDoorButton.setText("Tür öffnen");
        openDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDoorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webcamIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(openDoorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webcamIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(openDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDoorButtonActionPerformed
	panel.openDoor();
    }//GEN-LAST:event_openDoorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton openDoorButton;
    private javax.swing.JLabel webcamIconLabel;
    // End of variables declaration//GEN-END:variables

}
