/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DoorPanel.java
 *
 * Created on 30.03.2011, 13:24:57
 */

package de.htwhome.gui.panel;

import de.htwhome.devices.ConfigList;
import de.htwhome.devices.DeviceType;
import de.htwhome.devices.Panel;
import de.htwhome.utils.Config;

/**
 *
 * @author tim
 */
public class DoorPanel extends javax.swing.JPanel {
    Panel panel;

    /** Creates new form DoorPanel */
    public DoorPanel(Panel panel) {
	this.panel = panel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webcamIconLabel = new javax.swing.JLabel();
        openDoorButton = new javax.swing.JButton();

        webcamIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/htwhome/gui/panel/webcam.jpg"))); // NOI18N

        openDoorButton.setText("Tür öffnen");
        openDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDoorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(openDoorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(webcamIconLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webcamIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openDoorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDoorButtonActionPerformed
	ConfigList cfgList = panel.getConfigList();
	for(Config c: cfgList){
	    if(c.getDeviceType() == DeviceType.DoorOpener){
		int[] gidTab = c.getGidTab();
		if(gidTab != null){
		    for(int i=0; i < gidTab.length; i++){
			panel.openDoor(gidTab[i]);
		    }
		}
	    }
	}
    }//GEN-LAST:event_openDoorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton openDoorButton;
    private javax.swing.JLabel webcamIconLabel;
    // End of variables declaration//GEN-END:variables

}
