/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmergencyPanel.java
 *
 * Created on 30.03.2011, 14:51:02
 */

package de.htwhome.gui.panel;

import de.htwhome.devices.Panel;

/**
 *
 * @author tim
 */
public class EmergencyPanel extends javax.swing.JPanel {
    Panel panel;

    /** Creates new form EmergencyPanel */
    public EmergencyPanel(Panel panel) {
	this.panel = panel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fireAlarmButton = new javax.swing.JButton();
        weatherAlarmButton = new javax.swing.JButton();

        fireAlarmButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fireAlarmButton.setText("FEUER ALARM");
        fireAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireAlarmButtonActionPerformed(evt);
            }
        });

        weatherAlarmButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        weatherAlarmButton.setText("WETTER ALARM");
        weatherAlarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherAlarmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fireAlarmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(weatherAlarmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fireAlarmButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(weatherAlarmButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fireAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireAlarmButtonActionPerformed
	panel.sendFireAlarm();
    }//GEN-LAST:event_fireAlarmButtonActionPerformed

    private void weatherAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherAlarmButtonActionPerformed
	panel.sendWeatherAlarm();
    }//GEN-LAST:event_weatherAlarmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fireAlarmButton;
    private javax.swing.JButton weatherAlarmButton;
    // End of variables declaration//GEN-END:variables

}
