/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomePanel.java
 *
 * Created on 30.03.2011, 15:00:37
 */

package de.htwhome.gui.panel;

import de.htwhome.devices.DeviceType;
import de.htwhome.devices.Panel;
import de.htwhome.utils.Config;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author tim
 */
public class HomePanel extends javax.swing.JPanel implements ConfigChangeListener {
    Panel panel;
    ClockThread clockThread;

    /** Creates new form HomePanel */
    public HomePanel(Panel panel) {
	this.panel = panel;
	clockThread = new ClockThread(this);
        initComponents();
	clockThread.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thermometerLabel = new javax.swing.JLabel();
        anemomenterLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        lightStatusLabel = new javax.swing.JLabel();

        thermometerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thermometerLabel.setText("Temperatur:");

        anemomenterLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anemomenterLabel.setText("Wingeschwindigkeit:");

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        timeLabel.setText("12:45");

        statusLabel.setText("Status");

        lightStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lightStatusLabel.setText("Brennende Lampen: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thermometerLabel)
                            .addComponent(anemomenterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                        .addComponent(timeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lightStatusLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(statusLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(thermometerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(anemomenterLabel)
                        .addGap(105, 105, 105)
                        .addComponent(statusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(lightStatusLabel))
                    .addComponent(timeLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anemomenterLabel;
    private javax.swing.JLabel lightStatusLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel thermometerLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    public void changeEventReceived(ConfigChangeEvent evt) {
	Config cfg = evt.getConfig();
	if (cfg.getDeviceType() == DeviceType.Anemometer) {
	    anemomenterLabel.setText("Windgeschwindigkeit: " + cfg.getStatus() + "km/h");
	} else {
	    if (cfg.getDeviceType() == DeviceType.Thermometer) {
		thermometerLabel.setText("Temperatur: " + cfg.getStatus() + "°C");
	    } else {
		if (cfg.getDeviceType() == DeviceType.Light) {
		    int counter = 0;
		    for (Config c : panel.getConfigList()) {
			if (c.getDeviceType() == DeviceType.Light) {
			    if ((Boolean) c.getStatus() == true) {
				counter++;
			    }
			}
		    }
		    lightStatusLabel.setText("Brennende Lampen: " + counter);
		}
	    }
	}
    }

    public void updateClock(){
	Date d = new Date();
	timeLabel.setText(d.getHours() + ":" + d.getMinutes());
    }

}
