/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PercentSwitch.java
 *
 * Created on 19.03.2011, 22:37:27
 */
package de.htwhome.gui;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author christian, volkan
 */
public class PercentSwitch extends javax.swing.JFrame {
    // Variables declaration - do not modify

    private javax.swing.JLabel label;
    private javax.swing.JSlider slider;
    // End of variables declaration

    /** Creates new form PercentSwitch */
    public PercentSwitch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        slider = new javax.swing.JSlider();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(43, 43, 43).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(59, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(149, 149, 149).addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(57, Short.MAX_VALUE)));

        pack();
        slider.setValue(50);
        label.setText(Integer.toString(slider.getValue()));
        slider.addChangeListener(new MyChangeAction());
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PercentSwitch().setVisible(true);
            }
        });

    }

    public class MyChangeAction implements ChangeListener {

        public void stateChanged(ChangeEvent ce) {
            int value = slider.getValue();
            String str = Integer.toString(value);
            label.setText(str);
        }
    }
}
